COLUMNS_DESCRIPTION = {
    "report_date": {
        "description": """Date on which the characteristics were collected (data on employees)""",
        "column_type": "Date",
        "public": True,
        "is_unique": False,
        "is_unique_group": [],
    },
    "employee_id": {
        "description": "Employee personnel number",
        "column_type": "UInt64",
        "public": True,
        "is_unique": True,
        "is_unique_group": [],
    },
    "grade_num": {
        "description": "Employee grade",
        "column_type": "UInt32",
        "public": False,
        "is_unique": False,
        "is_unique_group": [],
    },
    "position_name": {
        "description": "Employee position",
        "column_type": "String",
        "public": True,
        "is_unique": False,
        "is_unique_group": [],
    },
    "unit_id_tree": {
        "description": "Tree structure",
        "column_type": "Array(String)",
        "public": True,
    },
    "person_surname": {
        "description": "Employee's last name",
        "column_type": "String",
        "public": True,
        "is_unique": False,
        "is_unique_group": ["person_patronimics", "person_name"],
    },
    "person_name": {
        "description": "Employee name",
        "column_type": "String",
        "public": True,
        "is_unique": False,
        "is_unique_group": ["person_patronimics", "person_surname"],
    },
    "person_patronimics": {
        "description": "Employee's middle name",
        "column_type": "String",
        "public": True,
        "is_unique": False,
        "is_unique_group": ["person_name", "person_surname"],
    },
    "gender": {
        "description": "Gender (1 -male, 2 -female, 0 -gender not specified)",
        "column_type": "UInt8",
        "public": False,
        "is_unique": False,
        "is_unique_group": [],
    },
    "age_y": {
        "description": "Age",
        "column_type": "UInt32",
        "public": False,
        "is_unique": False,
        "is_unique_group": [],
    },
    "wrk_email": {
        "description": "Employee internal mail",
        "column_type": "String",
        "public": True,
        "is_unique": True,
        "is_unique_group": [],
    },
    "ext_email": {
        "description": "Employee external mail",
        "column_type": "String",
        "public": True,
        "is_unique": True,
        "is_unique_group": [],
    },
    "employee_kipphn": {
        "description": "Employee phone number",
        "column_type": "String",
        "public": False,
        "is_unique": True,
    },
    "child_count": {
        "description": "Number of employee children",
        "column_type": "UInt8",
        "public": False,
        "is_unique": False,
        "is_unique_group": [],
    },
    "family_status": {
        "description": "Family status of the employee (0 -single, 1 -married, 2 -divorced, 3 -widower, 4 -unregistered marriage, 5 -not determined)",
        "column_type": "UInt8",
        "public": False,
        "is_unique": False,
        "is_unique_group": [],
    },
    "is_on_trial": {
        "description": "Flag -whether the employee is on a probationary period (0 -no, 1 -is)",
        "column_type": "UInt8",
        "public": False,
        "is_unique": False,
        "is_unique_group": [],
    },
    "sber_los_cnt_days": {
        "description": "Employee length of service in days",
        "column_type": "UInt32",
        "public": True,
        "is_unique": False,
        "is_unique_group": [],
    },
    "is_parental_leave": {
        "description": "Flag -whether the employee is on maternity leave (0 -no, 1 -is)",
        "column_type": "UInt8",
        "public": True,
        "is_unique": False,
        "is_unique_group": [],
    },
    "all_skills": {
        "description": "A list of all possible skills and competencies of an employee, presented in the form of a ClickHouse array structure",
        "column_type": "Array(String)",
        "public": True,
        "is_unique": False,
        "is_unique_group": [],
    },
    "days_since_salary_change_last": {
        "description": "Number of days that have passed since the employee's last salary increase",
        "column_type": "UInt32",
        "public": False,
        "is_unique": False,
        "is_unique_group": [],
    },
    "po_i_pernr": {
        "description": "Personnel number of the head of the Agile employee, product owner",
        "column_type": "UInt64",
        "public": True,
        "is_unique": False,
        "is_unique_group": [],
    },
    "fp_res": {
        "description": "Employee's quarterly performance appraisal with values"
        "(A -5, B -4, C -3, D -2, E -1), "
        "example of casting to a number for ranking: "
        "CASE WHEN fp_res = 'A' THEN 5 WHEN fp_res = 'B' THEN 4 WHEN fp_res = 'C' THEN 3"
        "WHEN fp_res = 'D' THEN 2 WHEN 'E' THEN 1 ELSE NULL END",
        "column_type": "String",
        "public": False,
        "is_unique": False,
        "is_unique_group": [],
    },
    "fp_comp": {
        "description": "Quarterly evaluation of an employee for values with values"
        "(A -5, B -4, C -3, D -2, E -1), "
        "example of casting to a number for ranking: "
        "CASE WHEN fp_comp = 'A' THEN 5 WHEN fp_comp = 'B' THEN 4 WHEN fp_comp = 'C' THEN 3 "
        "WHEN fp_comp = 'D' THEN 2 WHEN 'E' THEN 1 ELSE NULL END",
        "column_type": "String",
        "public": False,
        "is_unique": False,
        "is_unique_group": [],
    },
    "full_oshs_name": {
        "description": "Full name of the department",
        "column_type": "String",
        "public": True,
    },
    "all_succesors": {
        "description": "Personnel numbers of the employee's successors. The successor is not necessarily an employee from my team",
        "column_type": "Array(bigint)",
        "public": False,
        "is_unique": False,
        "is_unique_group": [],
    },
    "children_gender": {
        "description": "Gender of the employee's children (each element corresponds to one child and takes the values: 'm', 'f' and 'Blank')",
        "column_type": "Array(String)",
        "public": False,
        "is_unique": False,
        "is_unique_group": [],
    },
    "children_years": {
        "description": "An array collected from the ages of the employee's children, where each element corresponds to an individual child (either a number or 'Not filled'). The children_years and children_gender arrays are aligned and can be expanded together via arrayJoin",
        "column_type": "Array(String)",
        "public": False,
        "is_unique": False,
        "is_unique_group": [],
    },
    "lang_with_level": {
        "description": "Level of language proficiency of the employee, format ['language 1/language proficiency level 1', 'language 2/language proficiency level 2']",
        "column_type": "Array(String)",
        "public": False,
        "is_unique": False,
        "is_unique_group": [],
    },
    "tribe_name": {
        "description": "Name of the Agile tribe",
        "column_type": "String",
        "public": True,
        "is_unique": False,
        "is_unique_group": [],
    },
    "cluster_name": {
        "description": "Name of Agile cluster",
        "column_type": "String",
        "public": True,
        "is_unique": False,
        "is_unique_group": [],
    },
    "team_name": {
        "description": "Agile team name",
        "column_type": "String",
        "public": True,
        "is_unique": False,
        "is_unique_group": [],
    },
    "tribe_code": {
        "description": "The Agile Code",
        "column_type": "UInt64",
        "public": True,
        "is_unique": False,
        "is_unique_group": [],
    },
    "cluster_code": {
        "description": "At the Agile Cluster",
        "column_type": "UInt64",
        "public": True,
        "is_unique": False,
        "is_unique_group": [],
    },
    "team_code": {
        "description": "Team Agile Code",
        "column_type": "UInt64",
        "public": True,
        "is_unique": False,
        "is_unique_group": [],
    },
    "all_goals_desc": {
        "description": "All goals for the last quarter",
        "column_type": "Array(String)",
        "public": False,
        "is_unique": False,
        "is_unique_group": [],
    },
    "mean_value_completion": {
        "description": "Proportion of goals completed",
        "column_type": "Float32",
        "public": False,
        "is_unique": False,
        "is_unique_group": [],
    },
    "num_goals": {
        "description": "Number of targets",
        "column_type": "Int32",
        "public": False,
        "is_unique": False,
        "is_unique_group": [],
    },
    "not_completed_goals": {
        "description": "Number of unfulfilled goals",
        "column_type": "Int32",
        "public": False,
        "is_unique": False,
        "is_unique_group": [],
    },
    "risked_goals": {
        "description": "Number of critical targets",
        "column_type": "Int32",
        "public": False,
        "is_unique": False,
        "is_unique_group": [],
    },
    "achievement_desc": {
        "description": "Description of all recent achievements",
        "column_type": "Array(String)",
        "public": False,
        "is_unique": False,
        "is_unique_group": [],
    },
    "career_status": {
        "description": "Employee's career status -readiness to accept job offers (takes values: 'Open', 'Closed' and 'Not filled')",
        "column_type": "String",
        "public": False,
        "is_unique": False,
        "is_unique_group": [],
    },
    "university_name": {
        "description": "University name",
        "column_type": "String",
        "public": False,
        "is_unique": False,
        "is_unique_group": [],
    },
    "speciality_name": {
        "description": "Name of specialty from university",
        "column_type": "String",
        "public": False,
        "is_unique": False,
        "is_unique_group": [],
    },
    "date_finish_education": {
        "description": "Date of completion of education",
        "column_type": "Date",
        "public": False,
        "is_unique": False,
        "is_unique_group": [],
    },
    "lead_experience_years": {
        "description": "Number of years of management experience",
        "column_type": "Int64",
        "public": True,
        "is_unique": False,
        "is_unique_group": [],
    },
    "professionlevel_name": {
        "description": "Last job profile name",
        "column_type": "String",
        "public": True,
        "is_unique": False,
        "is_unique_group": [],
    },
    "vac_days": {
        "description": "Number of days left on vacation",
        "column_type": "Float32",
        "public": True,
        "is_unique": False,
        "is_unique_group": [],
    },
    "lid_tribe_i_pernr": {
        "description": "personnel number of the tribe leader",
        "column_type": "bigint",
        "public": True,
        "is_unique": False,
        "is_unique_group": [],
    },
    "lid_1_lvl_i_pernr": {
        "description": "personnel number of the head of the 1st level organization structure",
        "column_type": "bigint",
        "public": True,
        "is_unique": False,
        "is_unique_group": [],
    },
    "lid_2_lvl_i_pernr": {
        "description": "personnel number of the head of the 2st level organization structure",
        "column_type": "bigint",
        "public": True,
        "is_unique": False,
        "is_unique_group": [],
    },
    "lid_3_lvl_i_pernr": {
        "description": "personnel number of the head of the 3st level organization structure",
        "column_type": "bigint",
        "public": True,
        "is_unique": False,
        "is_unique_group": [],
    },
    "lid_cluster_i_pernr": {
        "description": "personnel number of the cluster manager",
        "column_type": "bigint",
        "public": True,
        "is_unique": False,
        "is_unique_group": [],
    },
    "it_lid_cluster_i_pernr": {
        "description": "IT personnel number of the cluster manager",
        "column_type": "bigint",
        "public": True,
        "is_unique": False,
        "is_unique_group": [],
    },
    "cur_tribe_i_pernr": {
        "description": "personnel number of the tribe curator",
        "column_type": "bigint",
        "public": True,
        "is_unique": False,
        "is_unique_group": [],
    }
}

AGILE_FIELDS_MAP = {
    "agile_team": "team_code",
    "agile_cluster": "cluster_code",
    "agile_tribe": "tribe_code",
}
